baseURL = "localhost:1313"
languageCode = "en-us"
title = "Chris DuBois"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Personal homepage for Chris DuBois."
#description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    email = "chris.dubois@gmail.com"
    twitter = "chrisdubois"
    linkedin = "https://www.linkedin.com/in/alexander-hans-collado-jr-9444146a"
    github = "chrisdubois"
    googlescholar = "https://scholar.google.com/citations?user=XXXXXXXXXXXXXXXXXXXXX=en"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "portrait_2.png"
    subtitle = "I'm Chris DuBois, an engineering manager at Apple."
    hero_right = ["I work on the [Siri WebAnswers](https://9to5mac.com/2019/08/27/spotlight-siri-web-answer/) team. We are an NLP-oriented R&D team. Our goal is to provide fast and direct answers to the questions people ask their devices.","**If you are interested in training and deploying ML models for a user-facing product, we are hiring!**","Prior to Apple, I was a Senior Data Scientist at a startup called Turi (formerly Dato and GraphLab) where I helped build the NLP functionalities as well as the recommender toolkit for Turi Create.","During graduate school, I focused on probabilistic models for relational events, e.g. communication or interaction within a social network. I obtained a Ph.D. from the Department of Statistics at University of California, Irvine, working with Padhraic Smyth and the DataLab. I also had the opportunity to do research internships at Google Research NY (with Daryl Pregibon) and Microsoft Research (with Chris Meek)."]

#    resume = "ResumeCollado.pdf"

[params.recent]
    enable = true
    title = "Recent work"

[params.previous]
    enable = true
    title = "Previous research"

[params.footer]
    enable = true
